name: Update

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check out github-tools
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: hugovk/github-tools
          path: github-tools
          persist-credentials: false

      - name: Check out CPython
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: python/cpython
          path: cpython
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Check less for testing
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: echo "NUMBER_TO_CHECK=20" >> "$GITHUB_ENV"

      - name: Check more for deploying
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: echo "NUMBER_TO_CHECK=10000" >> "$GITHUB_ENV"

      - name: Find open issues/PRs per team member
        run: |
          uv run github-tools/issues_by_dev.py --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Find orphaned backports
        run: |
          uv run github-tools/orphaned_backports.py --dry-run --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Find PRs and issues with "needs backport" labels
        run: |
          uv run github-tools/needs_backport.py cpython --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Find auto-merge PRs with failing CI
        run: |
          uv run github-tools/auto_merge_failing_ci.py --dry-run --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Find potential closeable issues
        run: |
          uv run github-tools/potential_closeable_issues.py --dry-run --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Prepare files
        run: |
          mkdir -p build/team/
          cp style.css ./*.html ./*.js ./*.svg build/
          ls github-tools/
          mv team/* build/team/
          mv github-tools/auto_merge_failing_ci.json build/
          mv github-tools/issues_by_dev.json build/
          mv github-tools/needs_backport.json build/
          mv github-tools/orphaned_backports.json build/
          mv github-tools/potential_closeable_issues.json build/
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Deploy 🚀
        if: |
          github.repository_owner == 'hugovk'
          && (
            github.event_name == 'schedule'
            || github.event_name == 'workflow_dispatch'
          )
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          folder: build
          clean: true
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dashboard
          path: build/
