name: Update

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  FORCE_COLOR: 1

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Check out github-tools
        uses: actions/checkout@v5
        with:
          repository: hugovk/github-tools
          path: github-tools
          persist-credentials: false

      - name: Check out CPython
        uses: actions/checkout@v5
        with:
          repository: python/cpython
          path: cpython
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Check less for testing
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: echo "NUMBER_TO_CHECK=20" >> "$GITHUB_ENV"

      - name: Check more for deploying
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: echo "NUMBER_TO_CHECK=10000" >> "$GITHUB_ENV"

      - name: Find open issues/PRs per team member
        run: |
          uv run github-tools/issues_by_dev.py --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Find orphaned backports
        run: |
          uv run github-tools/orphaned_backports.py --dry-run --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Find PRs and issues with "needs backport" labels
        run: |
          uv run github-tools/needs_backport.py cpython --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Find potential closeable issues
        run: |
          uv run github-tools/potential_closeable_issues.py --dry-run --json -n "$NUMBER_TO_CHECK"
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Prepare files
        run: |
          mkdir -p build/team/
          cp style.css ./*.html ./*.js ./*.svg build/
          ls github-tools/
          mv team/* build/team/
          mv github-tools/issues_by_dev.json build/
          mv github-tools/needs_backport.json build/
          mv github-tools/orphaned_backports.json build/
          mv github-tools/potential_closeable_issues.json build/
        env:
          GITHUB_TOOLS_TOKEN: ${{ secrets.DASHBOARD_GITHUB_TOOLS_TOKEN }}

      - name: Deploy 🚀
        if: |
          github.repository_owner == 'hugovk'
          && (
            github.event_name == 'schedule'
            || github.event_name == 'workflow_dispatch'
          )
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/upload-artifact@v4
        with:
          name: dashboard
          path: build/
